name: Build OpenWrt Kernel Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git subversion libncurses5-dev zlib1g-dev gawk python3 flex bison quilt cpio unzip

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git -b openwrt-23.05
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy custom config
      run: |
        cp .config openwrt/.config
        cd openwrt
        make defconfig

    - name: Build kernel module
      run: |
        cd openwrt
        make tools/install -j$(nproc)
        make toolchain/install -j$(nproc)
        make target/linux/compile -j$(nproc)
        make package/kernel/linux/compile V=s -j$(nproc)

    - name: Upload module
      uses: actions/upload-artifact@v4
      with:
        name: r8169-module
        path: openwrt/build_dir/target-aarch64_cortex-a76_musl/linux-bcm27xx_bcm2712/linux-6.6.*/drivers/net/ethernet/realtek/r8169.ko
